#!/usr/bin/env node

/**
 * Environment Setup Script
 * Helps configure .env file with proper values
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

const envPath = path.join(__dirname, '../.env');
const envExamplePath = path.join(__dirname, '../.env.example');

function question(query) {
  return new Promise((resolve) => rl.question(query, resolve));
}

async function setupEnv() {
  console.log('🔧 Setting up environment variables...\n');

  // Check if .env already exists
  if (fs.existsSync(envPath)) {
    const overwrite = await question('⚠️  .env file already exists. Overwrite? (y/N): ');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('❌ Setup cancelled.');
      rl.close();
      return;
    }
  }

  // Create .env.example if it doesn't exist
  if (!fs.existsSync(envExamplePath)) {
    const defaultEnv = `# Server Configuration
NODE_ENV=development
PORT=5000
API_VERSION=v1

# Database Configuration
DB_HOST=localhost
DB_PORT=3306
DB_USER=root
DB_PASSWORD=
DB_NAME=restaurant_db
DB_CONNECTION_LIMIT=10

# Redis Configuration
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_PASSWORD=
REDIS_DB=0

# JWT Configuration
JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
JWT_EXPIRES_IN=7d
JWT_REFRESH_SECRET=your-refresh-token-secret
JWT_REFRESH_EXPIRES_IN=30d

# CORS Configuration
CORS_ORIGIN=http://localhost:3000,http://localhost:3001
ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001

# Rate Limiting
RATE_LIMIT_WINDOW_MS=900000
RATE_LIMIT_MAX_REQUESTS=100

# Frontend URL
FRONTEND_URL=http://localhost:3000
`;
    fs.writeFileSync(envExamplePath, defaultEnv);
  }

  const env = {};

  // Server config
  console.log('\n📡 Server Configuration:');
  env.NODE_ENV = (await question('Environment (development/production) [development]: ')) || 'development';
  env.PORT = (await question('Port [5000]: ')) || '5000';
  env.API_VERSION = (await question('API Version [v1]: ')) || 'v1';

  // Database config
  console.log('\n🗄️  Database Configuration:');
  env.DB_HOST = (await question('MySQL Host [localhost]: ')) || 'localhost';
  env.DB_PORT = (await question('MySQL Port [3306]: ')) || '3306';
  env.DB_USER = (await question('MySQL User [root]: ')) || 'root';
  env.DB_PASSWORD = await question('MySQL Password: ');
  env.DB_NAME = (await question('Database Name [restaurant_db]: ')) || 'restaurant_db';
  env.DB_CONNECTION_LIMIT = (await question('Connection Limit [10]: ')) || '10';

  // Redis config
  console.log('\n🔴 Redis Configuration:');
  env.REDIS_HOST = (await question('Redis Host [localhost]: ')) || 'localhost';
  env.REDIS_PORT = (await question('Redis Port [6379]: ')) || '6379';
  env.REDIS_PASSWORD = await question('Redis Password (optional): ');
  env.REDIS_DB = (await question('Redis DB [0]: ')) || '0';

  // JWT config
  console.log('\n🔐 JWT Configuration:');
  env.JWT_SECRET = await question('JWT Secret (generate random string): ') || generateRandomString(32);
  env.JWT_EXPIRES_IN = (await question('JWT Expires In [7d]: ')) || '7d';
  env.JWT_REFRESH_SECRET = await question('JWT Refresh Secret: ') || generateRandomString(32);
  env.JWT_REFRESH_EXPIRES_IN = (await question('Refresh Token Expires In [30d]: ')) || '30d';

  // CORS config
  console.log('\n🌐 CORS Configuration:');
  env.CORS_ORIGIN = (await question('CORS Origins (comma-separated) [http://localhost:3000,http://localhost:3001]: ')) || 'http://localhost:3000,http://localhost:3001';
  env.ALLOWED_ORIGINS = env.CORS_ORIGIN;
  env.FRONTEND_URL = (await question('Frontend URL [http://localhost:3000]: ')) || 'http://localhost:3000';

  // Rate limiting
  console.log('\n⚡ Rate Limiting:');
  env.RATE_LIMIT_WINDOW_MS = (await question('Rate Limit Window (ms) [900000]: ')) || '900000';
  env.RATE_LIMIT_MAX_REQUESTS = (await question('Max Requests [100]: ')) || '100';

  // Build .env content
  let envContent = `# ============================================
# ENVIRONMENT CONFIGURATION
# Generated by setup-env.js
# ============================================

# Server Configuration
NODE_ENV=${env.NODE_ENV}
PORT=${env.PORT}
API_VERSION=${env.API_VERSION}

# Database Configuration
DB_HOST=${env.DB_HOST}
DB_PORT=${env.DB_PORT}
DB_USER=${env.DB_USER}
DB_PASSWORD=${env.DB_PASSWORD}
DB_NAME=${env.DB_NAME}
DB_CONNECTION_LIMIT=${env.DB_CONNECTION_LIMIT}

# Redis Configuration
REDIS_HOST=${env.REDIS_HOST}
REDIS_PORT=${env.REDIS_PORT}
REDIS_PASSWORD=${env.REDIS_PASSWORD || ''}
REDIS_DB=${env.REDIS_DB}

# JWT Configuration
JWT_SECRET=${env.JWT_SECRET}
JWT_EXPIRES_IN=${env.JWT_EXPIRES_IN}
JWT_REFRESH_SECRET=${env.JWT_REFRESH_SECRET}
JWT_REFRESH_EXPIRES_IN=${env.JWT_REFRESH_EXPIRES_IN}

# CORS Configuration
CORS_ORIGIN=${env.CORS_ORIGIN}
ALLOWED_ORIGINS=${env.ALLOWED_ORIGINS}
FRONTEND_URL=${env.FRONTEND_URL}

# Rate Limiting
RATE_LIMIT_WINDOW_MS=${env.RATE_LIMIT_WINDOW_MS}
RATE_LIMIT_MAX_REQUESTS=${env.RATE_LIMIT_MAX_REQUESTS}

# Logging
LOG_LEVEL=debug
LOG_FILE_PATH=./logs

# Scheduling
DYNAMIC_PRICING_CRON=0 */1 * * *
INVENTORY_ALERT_CRON=0 8 * * *
REPORT_GENERATION_CRON=0 0 * * *
`;

  // Write .env file
  fs.writeFileSync(envPath, envContent);
  console.log('\n✅ .env file created successfully!');
  console.log(`📁 Location: ${envPath}`);
  console.log('\n⚠️  Remember to:');
  console.log('   1. Keep JWT_SECRET secure and never commit to git');
  console.log('   2. Update database credentials if needed');
  console.log('   3. Configure Redis connection');
  console.log('   4. Run database migrations: npm run migrate');
  console.log('   5. Seed database: npm run seed');

  rl.close();
}

function generateRandomString(length) {
  const crypto = require('crypto');
  return crypto.randomBytes(length).toString('hex');
}

setupEnv().catch((error) => {
  console.error('❌ Error setting up environment:', error);
  rl.close();
  process.exit(1);
});

