// PM2 Ecosystem Configuration
// Manages both frontend and backend processes

module.exports = {
  apps: [
    {
      name: 'restaurant-backend',
      script: './backend/src/server.js',
      cwd: './backend',
      instances: 2, // Run 2 instances for load balancing
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'development',
        PORT: 5000,
        DB_HOST: 'localhost',
        DB_USER: 'root',
        DB_PASSWORD: 'password',
        DB_NAME: 'restaurant_db',
        JWT_SECRET: 'your-secret-key',
        REDIS_HOST: 'localhost',
        REDIS_PORT: 6379,
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 5000,
        DB_HOST: process.env.DB_HOST,
        DB_USER: process.env.DB_USER,
        DB_PASSWORD: process.env.DB_PASSWORD,
        DB_NAME: process.env.DB_NAME,
        JWT_SECRET: process.env.JWT_SECRET,
        REDIS_HOST: process.env.REDIS_HOST,
        REDIS_PORT: process.env.REDIS_PORT,
      },
      error_file: './logs/backend-error.log',
      out_file: './logs/backend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      node_args: '--max-old-space-size=2048',
    },
    {
      name: 'restaurant-frontend-customer',
      script: 'npm',
      args: 'run dev',
      cwd: './frontend-customer',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'development',
        PORT: 3000,
        NEXT_PUBLIC_API_URL: 'http://localhost:5000/api/v1',
        NEXT_PUBLIC_SOCKET_URL: 'http://localhost:5000',
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 3000,
        NEXT_PUBLIC_API_URL: process.env.API_URL,
        NEXT_PUBLIC_SOCKET_URL: process.env.SOCKET_URL,
      },
      error_file: './logs/frontend-customer-error.log',
      out_file: './logs/frontend-customer-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
    },
    {
      name: 'restaurant-frontend-admin',
      script: 'npm',
      args: 'run dev',
      cwd: './frontend-admin',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'development',
        PORT: 3001,
        VITE_API_URL: 'http://localhost:5000/api/v1',
        VITE_SOCKET_URL: 'http://localhost:5000',
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 3001,
        VITE_API_URL: process.env.API_URL,
        VITE_SOCKET_URL: process.env.SOCKET_URL,
      },
      error_file: './logs/frontend-admin-error.log',
      out_file: './logs/frontend-admin-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
    },
  ],
};

